# Generated by Django 3.2 on 2023-07-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='The subject of the question paper e.g English, Science, ...', max_length=100, null=True, verbose_name='Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
