# Generated by Django 3.2 on 2023-07-31 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0006_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Supporting link')),
                ('note', models.CharField(blank=True, help_text='A quick note about this supporting link. Must have words between 15 and 100.', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=15), django.core.validators.MaxLengthValidator(limit_value=100)], verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
