# Generated by Django 3.2 on 2023-07-31 22:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0009_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('body', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(1200)])),
                ('attachments', models.ManyToManyField(blank=True, null=True, to='eczmark.Attachment', verbose_name='Supporting images')),
                ('links', models.ManyToManyField(blank=True, null=True, to='eczmark.Link', verbose_name='Supporting link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Marker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
