# Generated by Django 3.2 on 2023-08-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0010_answer'),
    ]

    operations = [
    ]
