# Generated by Django 3.2 on 2023-07-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0010_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='eczmark.Attachment', verbose_name='Supporting images'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='links',
            field=models.ManyToManyField(blank=True, to='eczmark.Link', verbose_name='Supporting link'),
        ),
    ]
