# Generated by Django 3.2 on 2023-08-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0011_answer_alter_fields'),
    ]

    operations = [
    ]
