# Generated by Django 3.2 on 2023-08-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0012_refactor_field_name'),
    ]

    operations = [
    ]
