# Generated by Django 3.2 on 2023-08-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eczmark', '0013_refactor_verbose_name'),
    ]

    operations = [
    ]
